version: "3"

services:

  spring-server:
    image: spring-server
    container_name: spring-server
    build: ./server
    restart: always
    networks:
      - spring-network

  spring-proxy:
    image: nginx:stable
    container_name: spring-proxy
    restart: always
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - spring-network
    ports:
      - 80:80

networks:
  spring-network:
